services:
  - type: web
    name: document-converter
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT hybrid_app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: conversion-storage
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1